### ISSUE TITLE
编码错误

### ISSUE THREAD

**Issue by firstjack** [fan-lc/stats_gov#1]
今天在执行本代码时无法完成收集， 常常执行了1分钟就出错。能帮忙看下吗？谢谢了。
![QQ截图20190829192505](https://user-images.githubusercontent.com/13998458/63936580-bc9db980-ca92-11e9-8f03-cb433b53c6a5.jpg)

**Comment by fan-lc** [comment]
最近要重新获取数据看了下，是因为统计局网站加了反爬，访问过频会返回一个内置javascript的页面，而这个页面编码格式为utf8，不是gb18030。因为现在用了代理就不会有这个错误了。
